### ISSUE TITLE
Show dashboard after run complete?

### ISSUE THREAD

**Issue by bkj** [sherpa-ai/sherpa#103]
Hi -- Is there a way to show the dashboard after the run is complete?  Currently, once my optimization finishes, the dashboard turns off and I'm not able to see it anymore -- presumably there's some command to re-start the dashboard?

Thanks!

**Comment by LarsHH** [comment]
Hi @bkj ! There is actually a function to do this right now although it is a bit hidden: https://github.com/sherpa-ai/sherpa/blob/009a3552abe7786826e009b34629711e30689b83/sherpa/core.py#L666 The path is the output directory of the optimization

Best,
Lars
