### ISSUE TITLE
Allow custom parameters for mongodb

### ISSUE THREAD

**Issue by dfenn** [sherpa-ai/sherpa#13]
It would be useful to be able to pass custom parameters to mongodb (such as the location of a config file). 

In my particular case, I had to install mongodb in my user space since I don't have admin privileges, so I have to point it to a custom location for the config file.

**Comment by LarsHH** [comment]
That can absolutely be done. It would probably have to be via the arguments of the `sherpa.optimize` function.

I am actually considering to get rid of the MongoDB solution sooner or later in favor of something simpler.

**Comment by LarsHH** [comment]
Resolved: https://github.com/sherpa-ai/sherpa/pull/20/commits/211b313c625f714500583794b4b6b98e065c1ef7
