### ISSUE TITLE
Write logs for LocalScheduler

### ISSUE THREAD

**Issue by LarsHH** [sherpa-ai/sherpa#16]
Currently logs are output, but when something crashes Sherpa points to `output_dir/jobs/trial_<trial_id>.log` as reference to look for bugs. Either `LocalScheduler` needs to write its output to those files or the message needs to be changed. Whether it also writes to the command-line output can be decided.

**Comment by dosomder** [comment]
👍  Very important to debug trial scripts

**Comment by LarsHH** [comment]
Stdout and stderr are now written to `<output_dir>/jobs/trial_<id>.out` for `LocalScheduler`.
