### ISSUE TITLE
accounting for deep learning initialization

### ISSUE THREAD

**Issue by rakoczUCLA** [sherpa-ai/sherpa#22]
Initialization of the keras models between trials.
That sometimes has a large effect on results. I think a random seed is worth mentioning in the tutorial.

**Comment by LarsHH** [comment]
Hi @rakoczUCLA !
You are absolutely right, that can have a large impact. Did you have a particular tutorial in mind? Probably this one https://parameter-sherpa.readthedocs.io/en/latest/algorithms/algorithms.html would fit mentioning of the seed.

**Comment by rakoczUCLA** [comment]
I would put it in the basic ones: "A guide to SHERPA", "30 seconds from Keras to SHERPA".

**Comment by LarsHH** [comment]
Sounds good! We actually have an algorithm coming soon that will explicitly deal with this.

**Comment by LarsHH** [comment]
Update on this: there is the Repeat algorithm now https://github.com/sherpa-ai/sherpa/blob/14bc6aa7975e876bc9a60a33105fa3774cf4a403/sherpa/algorithms/core.py#L83 to deal with this. Still needs to be added to the documentation though.
