### ISSUE TITLE
Support for new algorithms

### ISSUE THREAD

**Issue by anirudhacharya** [sherpa-ai/sherpa#29]
- [x] Hyperband - https://www.sysml.cc/doc/100.pdf
 - [ ] Parzen-window estimator - as per https://github.com/sherpa-ai/sherpa/pull/27#issuecomment-473526343 hyperopt can be an option.
 - [ ] Particle Swarm Optimization

**Comment by LarsHH** [comment]
Asynchronous Successive Halving is implemented ( https://github.com/sherpa-ai/sherpa/blob/8d6029307d27a2cef953c0ca36f197f14d321815/sherpa/algorithms/successive_halving.py#L27 ) which according to https://arxiv.org/pdf/1810.05934.pdf outperforms Hyperband. ASHA can actually be used to do Hyperband by iterating over different settings, but I'll leave that to future work for now.

**Comment by LarsHH** [comment]
Looks like https://github.com/DEAP could be a good starting point for the particle swarm optimization

**Comment by LarsHH** [comment]
Converted to cards in projects:
https://github.com/sherpa-ai/sherpa/projects/1#card-28466175
https://github.com/sherpa-ai/sherpa/projects/1#card-28466208
