### ISSUE TITLE
How to access SHERPA Dashboard when working at colab and how to save study there?

### ISSUE THREAD

**Issue by daraghimo** [sherpa-ai/sherpa#41]
Peace to everyone
I am a beginner working on keras at colab
I know that my model is working because I see the training when setting verbose to 1

http://172.28.0.2:8880 : This site can’t be reached 172.28.0.2 took too long to respond
http://localhost:8880 :  This site can’t be reached localhost refused to connect.
I tried reading : 
https://cloud.google.com/deep-learning-vm/docs/jupyter
https://research.google.com/colaboratory/local-runtimes.html
but I don't know what the matter is exactly about and what to do
**another question please** 
after creating sherpa_study.csv at my google drive and when trying
`study.save(output_dir='drive/My Drive/pyton/sherpa_study.csv')`
I get 
`NotADirectoryError: [Errno 20] Not a directory: 'drive/My Drive/pyton/sherpa_study.csv/config.pkl'`

finally I want to say that your library is really awesome. I tried many other tools with my functional api multi-output regression model without success. your library seems to work and the basic part is easy to use.

**Comment by LarsHH** [comment]
Hi @daraghimo ,
Thanks for the kind words. Congrats to getting it to work on Colab in the first place. I hadn't tried that yet.

The first one: is there documentation on how to run Tensorboard on Colab? That might help to deal with this issue. In general I assume you will somehow have to pipe that port back to your machine.

The second part may be an issue with the path. I'm not sure how Colab works, but would it be possible to try `output_dir="."` or something similar just to verify it is not the path name that causes the problem?

**Comment by LarsHH** [comment]
Hi @daraghimo ,
Any updates on this? Did any of those things help? I may try this on Colab myself and add a tutorial for that, but wanted to check if you had any success.

**Comment by LarsHH** [comment]
Follow up: I created a Colab notebook and tunneled the dashboard using NGROK: https://colab.research.google.com/drive/1I19R1GfKPjlgNdHlxJwNC4PitvySsdon . I followed this tutorial for the tunneling: https://www.dlology.com/blog/quick-guide-to-run-tensorboard-in-google-colab/ .
