### ISSUE TITLE
GPyOpt producing real values for discrete parameters

### ISSUE THREAD

**Issue by AlexFuster** [sherpa-ai/sherpa#48]
Running the example mnist_mlp, GPyOpt gave me the following configuration:
Trial 4:	{'num_units': 116.0, 'activation': 'relu'}
This obviously makes Keras to produce an error, as it does not admit real values for number of units
I know this is probably due to the changes made to solve the issue #42

**Comment by LarsHH** [comment]
Nice catch! Thanks. Yeah this was part of me changing the conversion from
Sherpa parameters to GPyOpt Parameters and the tests didn’t catch it. I’ll
fix it later today.

**Comment by LarsHH** [comment]
Solved in commit https://github.com/sherpa-ai/sherpa/commit/0fc629035f7e1e5f40a3e895e96817e81c849697
