### ISSUE TITLE
Dashboard not accessible

### ISSUE THREAD

**Issue by martsalz** [sherpa-ai/sherpa#59]
I have installed all required packages and executed the above example. The web interface is not reachable. An error message etc. is not displayed - what could be the reason?

Running in a venv under Python 3.5

![image](https://user-images.githubusercontent.com/12211578/64472035-cf7e5100-d158-11e9-93a4-25ce79398fb1.png)

![image](https://user-images.githubusercontent.com/12211578/64472069-1ff5ae80-d159-11e9-8e1b-54ecbc5fe6a8.png)

**Comment by LarsHH** [comment]
Hi Martin,
Did you try both of the provided URLs? If there is no error message I’m assuming the dashboard is running but the displayed address is wrong. The port should be correct. Are you on MacOS or Ubuntu?

**Comment by martsalz** [comment]
Yes, both.
I installed Sherpa under Ubuntu 16.04.

**Comment by martsalz** [comment]
(This was a "clean" installation without other software or packages)

**Comment by martsalz** [comment]
Which system do you use for Sherpa? 
Which Python version? 
A virtual environment?

**Comment by sherpa-ai** [comment]
I have two setups:

* MacOS and Python 3.6 in a virtual environment
* CentOS  and Python 3.6 in a conda environment. This one I only access remotely though.

I have just merged a pull request https://github.com/sherpa-ai/sherpa/pull/51 that I'm wondering if it could help with your issue. When you get a chance could you pull from master and try again? If you pip-installed can you clone from Github instead? If you previously pip installed and are cloning now let me know if you run into any issues in setting up - it is mainly that the PyPi version is always a little bit behind the Github version

**Comment by LarsHH** [comment]
I have two setups:

* MacOS and Python 3.6 in a virtual environment
* CentOS  and Python 3.6 in a conda environment. This one I only access remotely though.

I have just merged a pull request https://github.com/sherpa-ai/sherpa/pull/51 that I'm wondering if it could help with your issue. When you get a chance could you pull from master and try again? If you pip-installed can you clone from Github instead? If you previously pip installed and are cloning now let me know if you run into any issues in setting up - it is mainly that the PyPi version is always a little bit behind the Github version.

**Comment by martsalz** [comment]
It seems to be working now. I executed `simple.py`, probably the webserver was shut down immediately afterwards.

When I run the `simple.ipynb` or `mnist_mlp.ipynb`, the server is started and can be reached via the browser. However, the display in the upper area irritates me slightly:

![image](https://user-images.githubusercontent.com/12211578/64539325-97c10600-d31e-11e9-81d4-1659cb610674.png)

(tested with Firefox and Chrome)

**Comment by LarsHH** [comment]
Could you pull once more from master and rerun? I just added a fix for this.

**Comment by LarsHH** [comment]
The file `sherpa/sherpa/app/templates/index.html` should have this on line 4: ```<div class="mdl-card mdl-shadow--2dp" style="position: absolute; height: 60%; width: 100%;">```

**Comment by martsalz** [comment]
It works, thanks.
