### ISSUE TITLE
Population Based Training algorithm: Difference between parameters and parameter_range

### ISSUE THREAD

**Issue by martsalz** [sherpa-ai/sherpa#62]
Could you please explain the exact difference between `parameters` and `parameter_range`?
Why are the parameters specified twice?

![image](https://user-images.githubusercontent.com/12211578/64566163-98c15a00-d355-11e9-89c1-11bf7d84fc40.png)

https://parameter-sherpa.readthedocs.io/en/latest/algorithms/pbt.html

Thanks.

**Comment by LarsHH** [comment]
The `parameter_range` argument defines the range in which the parameter can evolve whereas for PBT the actual parameter definitions define on what range the parameters will be initialized. Here "evolve" corresponds to the fact that PBT perturbs parameters. So the user may want to set the range that values can evolve in to be larger than the initialization range. For example for learning rates we may only want to initialize within a certain range but then allow to be perturbed to much smaller values than that.
