### ISSUE TITLE
Possible typo on guide website:

### ISSUE THREAD

**Issue by jbae11** [sherpa-ai/sherpa#88]
in https://parameter-sherpa.readthedocs.io/en/latest/gettingstarted/guide.html

I think the second line should be 
`model = init_model(trial.parameters)` 

![image](https://user-images.githubusercontent.com/20345275/73542396-9b0a7a80-4402-11ea-8d74-e7cc08107990.png)

I might be wrong, thanks for the tool!

**Comment by LarsHH** [comment]
You're right. Thanks for the pull request!
