### ISSUE TITLE
Using shlex to split runner_command

### ISSUE THREAD

**Issue by nasimrahaman** [sherpa-ai/sherpa#90]
First things first, great work on the library! 👍 

This (very minor) issue is regarding [this line](https://github.com/sherpa-ai/sherpa/blob/master/sherpa/core.py#L637), where I believe `shlex.split(command)` would be more appropriate (instead of `command.split(' ')` (`shlex` is a builtin module). It would enable commands like `--arg1 "Argument 1" --arg2 "Argument 2"`. It would also be nice if `command` could be a pre-parsed list.

**Comment by LarsHH** [comment]
Resolved in #95
