### ISSUE TITLE
Only install enum34 for old versions of Python

### ISSUE THREAD

**Issue by tpanza** [sherpa-ai/sherpa#91]
The [requirements.txt](https://github.com/sherpa-ai/sherpa/blob/master/requirements.txt#L8) file and [setup.py](https://github.com/sherpa-ai/sherpa/blob/master/setup.py#L36) will always install the `enum34` package.

From what I understand about the [enum34](https://pypi.org/project/enum34/) package, it backports the Python 3.4 Enum to older versions of Python (3.3, 3.2, 3.1, 2.7, 2.6, 2.5, and 2.4).

Therefore, if the user is running with a new enough version of Python, the `enum34` package is not required. 

Most importantly, having `enum34` installed into a Python 3.4+ environment [will cause problems](https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag) since they are [installed to the same location](https://stackoverflow.com/a/36991275/2491761).

In the requirements.txt file, `enum34` could easily be skipped for newer Python versions:

```
enum34; python_version < '3.4'
```

In the setup.py file, the Python version could easily be read from the [sys.version_info](https://docs.python.org/3/library/sys.html#sys.version_info) tuple.

(As a separate question, why are the install requirements listed in both requirements.txt and setup.py?)

**Comment by tpanza** [comment]
@LarsHH thoughts on this?

**Comment by LarsHH** [comment]
Hey @tpanza ,
Thanks for pointing this out and sorry for the long time to get back to you. 

```
enum34; python_version < '3.4'
```

Sounds like a good solution to me. Regarding your second question, I think that's a mistake. I will look into resolving these. Are you able to fix this locally for yourself right now?

**Comment by tpanza** [comment]
Hi @LarsHH . Yes, I am able to fix and workaround locally: `pip uninstall enum34`

**Comment by LarsHH** [comment]
https://github.com/sherpa-ai/sherpa/pull/94
